
# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'fkiddyapp' do
	pod 'Alamofire', '~>4.5'
  # Comment the next line if you don't want to use dynamic frameworks


  # Pods for fkiddyapp

end
